### ISSUE TITLE
add support for debounce && throttle ?

### ISSUE THREAD

**Issue by mydearxym** [mbasso/react-decoration#2]
**General Information**
- [ ] Bug
- [x] Improvement
- [ ] Feature
- [ ] Other

**Description**

[debounce](https://github.com/jayphelps/core-decorators.js#debounce) and [throttle](https://github.com/jayphelps/core-decorators.js#throttle) are very common in dev, could it be added?

**Comment by mbasso** [comment]
Hi @mydearxym,
yes, good idea. I'll start developing them in the next few days

**Comment by mydearxym** [comment]
great! looking forward 👍

**Comment by mbasso** [comment]
@mydearxym I have just published react-decoration@1.3.0 with debounce and throttle decorators 🎉 🎊 , check it [here](https://github.com/mbasso/react-decoration/releases/tag/1.3.0).
Let me know if I can close this issue

**Comment by mydearxym** [comment]
very cool 👍   it looks perfect !

and it's nice if  [babel-plugin-transform-decorators](https://www.npmjs.com/package/babel-plugin-transform-decorators) is added to docs too

**Comment by mbasso** [comment]
[Here](https://github.com/mbasso/react-decoration/blob/master/docs/Introduction.md) is the new introduction that explains how to parse decorators with babel.

**Comment by mydearxym** [comment]
great ! we can close the issue , thanks very much !
