### ISSUE TITLE
Missing /lib folder - Unable to use the package

### ISSUE THREAD

**Issue by igghera** [mbasso/react-decoration#5]
**General Information**

- [x ] Bug
- [ ] Improvement
- [ ] Feature
- [ ] Other

**Description**

I have installed the package in my project. At first Atom was complaining that it couldn't find the module:

<img width="953" alt="screen shot 2016-11-14 at 12 33 51" src="https://cloud.githubusercontent.com/assets/578103/20263360/a578e5ee-aa66-11e6-9fee-634ca2902ecd.png">

That's probably because the "main" field in the `package.json` file is set to "lib/index.js", but there's no `lib` folder in the project.
Looking at the npm scripts I found the `build` script, that should generate the `lib` folder, but I'm not sure when that's supposed to happen. Maybe as a `postinstall` script? 

**Steps to reproduce**

Install the package via `npm install` and import one of the decorators in a project.

**Versions**

- react-decoration: 1.4.0
- Browser: No browser needed, happens on node level

**Comment by mbasso** [comment]
Hi,
I've tried to install react-decoration@1.4.0 but I've not been able to reproduce this issue. Can you try to install it again with `npm install --save react-decoration`?
Install also its peer dependency react-addons-perf: `npm install --save-dev react-addons-perf`

**Comment by igghera** [comment]
Hey Matteo,

thanks for the quick reply :)

I have tried installing `react-addons-perf` as well, but the result is the same. 
Basically the `lib` folder is missing.
Do you have any idea why it could be missing?

Oh, I forgot to mention: these decorators are great, I love the idea. Thanks for it!

**Comment by mbasso** [comment]
Thank you, I'm glad you like it :)

Unfortunately, I have no ideas at the moment.
As you can see [here](https://travis-ci.org/mbasso/react-decoration/jobs/173720719#L1771),  `npm run build` creates `lib` folder that is published to npm.
It seems working fine [here](https://runkit.com/57f0be77f5fa9d140082e891/582a07e2e3431f0014099baa). I have also tried to install it in a project.
Can you please run the following and copy/paste the output here?

``` bash
npm uninstall react-decoration
npm install --save react-decoration@latest
```

**Comment by igghera** [comment]
This is the output

```
$ npm install --save react-decoration@latest
opa@0.1.0 /Users/andrea/dev/opa
└─┬ react-decoration@1.4.0
  └── autobind-decorator@1.3.3
```

By the way I can survive without the decorators, it's not a matter of life or death. I just liked them so much, especially the autobind one!

Also, I'm italian so if you prefer we can switch to that language :)

**Comment by mbasso** [comment]
I'd like to switch language, but I think that we should continue this conversation in english, in this way other contributors might help us.

I think that we can delete `node_modules` folder and then try:

``` bash
npm cache clean
npm install --save react-decoration@latest
```

If the error persists can you try to install `react-decoration@1.3.0`?
I'm sure that [this release works well](https://github.com/mbasso/react-decoration/issues/4), so we can determine that is a problem related to a specific version of npm/node.

Can you please provide the following?
- npm version
- node version
- content of `node_modules/react-decoration` folder

If you are using a boilerplate, please, provide also its link

**Comment by mbasso** [comment]
@igghera Do you have any news about this issue?

**Comment by mbasso** [comment]
I’m closing this issue because it has been inactive for a few weeks.
Please reopen if you still encounter this issue :)

Thank you!

**Comment by JensHernie** [comment]
spaghetti
