### ISSUE TITLE
Can you provide a simple example for each decorator?

### ISSUE THREAD

**Issue by lee1994522** [mbasso/react-decoration#6]
Can you provide a simple example for each decorator?

**Comment by mbasso** [comment]
Hi,
in [docs folder](https://github.com/mbasso/react-decoration/tree/master/docs) there is a simple explanation and a simple example for each decorator, components' name in the table of contents are link to these specs. [Here](https://github.com/mbasso/react-decoration/blob/master/docs/components/bindProps.md) is an example of one of these pages.

**Comment by lee1994522** [comment]
Sorry,I didn't look carefully ,thank you very much

**Comment by mbasso** [comment]
You're welcome :)
