### ISSUE TITLE
React-Native Compatibility

### ISSUE THREAD

**Issue by robertherber** [mbasso/react-decoration#8]
**General Information**

- [ ] Bug
- [x] Improvement
- [ ] Feature
- [ ] Other

**Description**

`react-addons-perf` is not compatible with React-Native. The best would be if `@perf` provided alternative functionality that worked with React-Native. 

Right now you'll have to import each decorator directly to not trigger an import of `react-addons-perf` - a decent first step would be to import it dynamically so you only need to install `react-addons-perf` for the `@perf` decorator.

**Steps to reproduce**

1. Install `react-decoration`
2. Don't install `react-addons-perf`
3. Import any decorator from the main export.

**Versions**

- react-decoration: 1.4.1

**Comment by mbasso** [comment]
Hi robert,
thank you for opening this issue, I'll look for a solution as soon as possible.

> `react-addons-perf` is not compatible with React-Native. The best would be if `@perf` provided alternative functionality that worked with React-Native.

I've found [this](https://facebook.github.io/react-native/docs/performance.html#profiling) page that say that `react-addons-perf` is compatible with `react-native`, is it an error in the doc or are you referring to an older version (<0.45)? Have you any idea about alternative functionality? Are you using others packages to do that in `react-native`?

I've found this in a lot of answers on stackoverflow and github:
```js
import Perf from 'ReactPerf';
```
does this code represent the right way to import performance utils in `react-native`?

> Right now you'll have to import each decorator directly to not trigger an import of `react-addons-perf` - a decent first step would be to import it dynamically so you only need to install `react-addons-perf` for the `@perf` decorator.

This is a problem that have to be resolved shortly. Have you any links about optional dependencies? docs, blog posts... I know that webpack has a dynamic import but I think that the package has to be installed anyway...

**Comment by mbasso** [comment]
I'll close this issue because `react-addons-perf` [no longer works with react@16](https://facebook.github.io/react/blog/#react-addons). we'll create a new decorator after that the react team will release a new version of this tool in the future
